# Generated by Django 2.1 on 2018-09-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='uname',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registertable',
            name='year',
            field=models.IntegerField(),
        ),
    ]
