# Generated by Django 2.1 on 2018-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('reg_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='userid',
        ),
    ]
