# Generated by Django 2.1 on 2018-09-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('sapid', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=120)),
                ('date', models.DateField()),
                ('prof', models.TextField(max_length=600)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('institute', models.CharField(max_length=200)),
            ],
        ),
    ]
