# Generated by Django 2.1 on 2018-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='id',
        ),
        migrations.AddField(
            model_name='edit',
            name='qid',
            field=models.ManyToManyField(to='Teachers.qualification'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
